-- =====================================================================
-- Seed danh mục — SINH TỰ ĐỘNG từ DATA UV DRKAM 2026.xlsx
-- Đừng sửa tay file này; sửa tools/gen_seed.py rồi chạy: python tools/gen_seed.py
-- =====================================================================

-- Chốt an toàn: dừng nếu đây không phải project riêng của app tuyển dụng.
-- Hàm này do 0001_init.sql tạo ra, project khác không có nên sẽ báo lỗi ngay.
select public.f_kiem_tra_project();

insert into public.catalogs (type, value, sort_order, meta) values
  ('position', 'Ads', 0, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Ads chạy kênh AI', 1, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Biên kịch Tiktok', 2, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Booking', 3, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Content', 4, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'CSKH off', 5, '{"department": "Sale offline", "level": "Nhân viên"}'::jsonb),
  ('position', 'CSKH on', 6, '{"department": "Sale online", "level": "Nhân viên"}'::jsonb),
  ('position', 'Designer', 7, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Digital Lead', 8, '{"department": "Marketing", "level": "Trưởng phòng"}'::jsonb),
  ('position', 'Đóng hàng (Fulltime)', 9, '{"department": "Kho vận", "level": "Nhân viên"}'::jsonb),
  ('position', 'Đóng hàng (Partime)', 10, '{"department": "Kho vận", "level": "Partime"}'::jsonb),
  ('position', 'HR', 11, '{"department": "HCNS", "level": "Nhân viên"}'::jsonb),
  ('position', 'HRM', 12, '{"department": "HCNS", "level": "Trưởng phòng"}'::jsonb),
  ('position', 'Kế toán sàn', 13, '{"department": "Kế toán", "level": "Nhân viên"}'::jsonb),
  ('position', 'Live full', 14, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Live Part', 15, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Marketing AI', 16, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Media', 17, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Sale off', 18, '{"department": "Sale offline", "level": "Nhân viên"}'::jsonb),
  ('position', 'Sale On', 19, '{"department": "Sale online", "level": "Nhân viên"}'::jsonb),
  ('position', 'Trưởng phòng Marketing', 20, '{"department": "Marketing", "level": "Trưởng phòng"}'::jsonb),
  ('position', 'Trợ lý TGD', 21, '{"department": "BGĐ", "level": "Nhân viên"}'::jsonb),
  ('position', 'TTS HR', 22, '{"department": "HCNS", "level": "Thực tập sinh"}'::jsonb),
  ('position', 'TTS MKT', 23, '{"department": "Marketing", "level": "Thực tập sinh"}'::jsonb),
  ('position', 'Vận hành Sàn', 24, '{"department": "Sale online", "level": "Nhân viên"}'::jsonb),
  ('position', 'Kế toán kho', 25, '{"department": "Kế toán", "level": "Nhân viên"}'::jsonb),
  ('position', 'Lead Live', 26, '{"department": "Marketing", "level": "Trưởng nhóm"}'::jsonb),
  ('position', 'Vận Đơn', 27, '{"department": "Kho vận", "level": "Nhân viên"}'::jsonb),
  ('position', 'Kế toán viên', 28, '{"department": "Kế toán", "level": "Nhân viên"}'::jsonb),
  ('position', 'Kế toán kiêm Hành chính', 29, '{"department": "Kế toán", "level": "Nhân viên"}'::jsonb),
  ('position', 'Lead Content', 30, '{"department": "Marketing", "level": "Trưởng nhóm"}'::jsonb),
  ('position', 'Brand leader', 31, '{"department": "Marketing", "level": "Trưởng phòng"}'::jsonb),
  ('position', 'TTS Media', 32, '{"department": "Marketing", "level": "Thực tập sinh"}'::jsonb),
  ('position', 'TTS Booking', 33, '{"department": "Marketing", "level": "Thực tập sinh"}'::jsonb),
  ('position', 'TTS Content', 34, '{"department": "Marketing", "level": "Thực tập sinh"}'::jsonb),
  ('position', 'Trợ live', 35, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'TTS kế toán', 36, '{"department": "Kế toán", "level": "Thực tập sinh"}'::jsonb),
  ('position', 'Telesale', 37, '{"department": "Sale online", "level": "Nhân viên"}'::jsonb),
  ('position', 'Kế toán trưởng', 38, '{"department": "Kế toán", "level": "Trưởng phòng"}'::jsonb),
  ('position', 'Quản lý kho', 39, '{"department": "Kho vận", "level": "Trưởng phòng"}'::jsonb),
  ('position', 'NV kho vận', 40, '{"department": "Kho vận", "level": "Nhân viên"}'::jsonb),
  ('position', 'Leader CSKH On', 41, '{"department": "Sale online", "level": "Trưởng nhóm"}'::jsonb),
  ('position', 'Kế toán tổng hợp', 42, '{"department": "Kế toán", "level": "Nhân viên"}'::jsonb),
  ('position', 'Digital Marketing', 43, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Kế toán nội bộ', 44, '{"department": "Kế toán", "level": "Nhân viên"}'::jsonb),
  ('position', 'SEO WEB', 45, '{"department": "Marketing", "level": "Nhân viên"}'::jsonb),
  ('position', 'Kế toán công nợ', 46, '{"department": "Kế toán", "level": "Nhân viên"}'::jsonb),
  ('position', 'HCNS', 47, '{"department": "HCNS", "level": "Nhân viên"}'::jsonb),
  ('position', 'Kế toán Thuế', 48, '{"department": "Kế toán", "level": "Nhân viên"}'::jsonb),
  ('department', 'BGĐ', 0, '{}'),
  ('department', 'HCNS', 1, '{}'),
  ('department', 'Kế toán', 2, '{}'),
  ('department', 'Kho vận', 3, '{}'),
  ('department', 'Marketing', 4, '{}'),
  ('department', 'Sale online', 5, '{}'),
  ('department', 'Sale offline', 6, '{}'),
  ('level', 'Giám đốc', 0, '{}'),
  ('level', 'Nhân viên', 1, '{}'),
  ('level', 'Thực tập sinh', 2, '{}'),
  ('level', 'Trưởng phòng', 3, '{}'),
  ('level', 'Trưởng nhóm', 4, '{}'),
  ('level', 'Partime', 5, '{}'),
  ('region', 'Hà Nội', 0, '{}'),
  ('region', 'TP.HCM', 1, '{}'),
  ('gender', 'Nam', 0, '{}'),
  ('gender', 'Nữ', 1, '{}'),
  ('province', 'An Giang', 0, '{}'),
  ('province', 'Bà Rịa - Vũng Tàu', 1, '{}'),
  ('province', 'Bắc Giang', 2, '{}'),
  ('province', 'Bắc Kạn', 3, '{}'),
  ('province', 'Bạc Liêu', 4, '{}'),
  ('province', 'Bắc Ninh', 5, '{}'),
  ('province', 'Bến Tre', 6, '{}'),
  ('province', 'Bình Định', 7, '{}'),
  ('province', 'Bình Dương', 8, '{}'),
  ('province', 'Bình Phước', 9, '{}'),
  ('province', 'Bình Thuận', 10, '{}'),
  ('province', 'Cà Mau', 11, '{}'),
  ('province', 'Cần Thơ', 12, '{}'),
  ('province', 'Cao Bằng', 13, '{}'),
  ('province', 'Đà Nẵng', 14, '{}'),
  ('province', 'Đắk Lắk', 15, '{}'),
  ('province', 'Đắk Nông', 16, '{}'),
  ('province', 'Điện Biên', 17, '{}'),
  ('province', 'Đồng Nai', 18, '{}'),
  ('province', 'Đồng Tháp', 19, '{}'),
  ('province', 'Gia Lai', 20, '{}'),
  ('province', 'Hà Giang', 21, '{}'),
  ('province', 'Hà Nam', 22, '{}'),
  ('province', 'Hà Nội', 23, '{}'),
  ('province', 'Hà Tĩnh', 24, '{}'),
  ('province', 'Hải Dương', 25, '{}'),
  ('province', 'Hải Phòng', 26, '{}'),
  ('province', 'Hậu Giang', 27, '{}'),
  ('province', 'TP. Hồ Chí Minh', 28, '{}'),
  ('province', 'Hòa Bình', 29, '{}'),
  ('province', 'Hưng Yên', 30, '{}'),
  ('province', 'Khánh Hòa', 31, '{}'),
  ('province', 'Kiên Giang', 32, '{}'),
  ('province', 'Kon Tum', 33, '{}'),
  ('province', 'Lai Châu', 34, '{}'),
  ('province', 'Lâm Đồng', 35, '{}'),
  ('province', 'Lạng Sơn', 36, '{}'),
  ('province', 'Lào Cai', 37, '{}'),
  ('province', 'Long An', 38, '{}'),
  ('province', 'Nam Định', 39, '{}'),
  ('province', 'Nghệ An', 40, '{}'),
  ('province', 'Ninh Bình', 41, '{}'),
  ('province', 'Ninh Thuận', 42, '{}'),
  ('province', 'Phú Thọ', 43, '{}'),
  ('province', 'Phú Yên', 44, '{}'),
  ('province', 'Quảng Bình', 45, '{}'),
  ('province', 'Quảng Nam', 46, '{}'),
  ('province', 'Quảng Ngãi', 47, '{}'),
  ('province', 'Quảng Ninh', 48, '{}'),
  ('province', 'Quảng Trị', 49, '{}'),
  ('province', 'Sóc Trăng', 50, '{}'),
  ('province', 'Sơn La', 51, '{}'),
  ('province', 'Tây Ninh', 52, '{}'),
  ('province', 'Thái Bình', 53, '{}'),
  ('province', 'Thái Nguyên', 54, '{}'),
  ('province', 'Thanh Hóa', 55, '{}'),
  ('province', 'Thừa Thiên - Huế', 56, '{}'),
  ('province', 'Tiền Giang', 57, '{}'),
  ('province', 'Trà Vinh', 58, '{}'),
  ('province', 'Tuyên Quang', 59, '{}'),
  ('province', 'Vĩnh Long', 60, '{}'),
  ('province', 'Vĩnh Phúc', 61, '{}'),
  ('province', 'Yên Bái', 62, '{}'),
  ('source', 'CareerLink', 0, '{}'),
  ('source', 'CareerViet', 1, '{}'),
  ('source', 'Chợ Tốt', 2, '{}'),
  ('source', 'Facebook', 3, '{}'),
  ('source', 'Hunt', 4, '{}'),
  ('source', 'LinkedIn', 5, '{}'),
  ('source', 'Nội bộ giới thiệu', 6, '{}'),
  ('source', 'Taki', 7, '{}'),
  ('source', 'TopCV', 8, '{}'),
  ('source', 'TradeCV', 9, '{}'),
  ('source', 'Vieclam24h', 10, '{}'),
  ('source', 'Vietnamworks', 11, '{}'),
  ('source', 'Ybox', 12, '{}'),
  ('source', 'Zalo', 13, '{}'),
  ('source', 'Vieclamcantho', 14, '{}'),
  ('source', 'JobsGO', 15, '{}'),
  ('source', 'Cá nhân', 16, '{}'),
  ('source', 'Web công ty', 17, '{}'),
  ('source', 'Pharma360', 18, '{}'),
  ('source', 'Mail', 19, '{}'),
  ('source', 'TopCV (chủ động lọc)', 20, '{}'),
  ('source', 'Glints', 21, '{}'),
  ('source', 'Joboko', 22, '{}'),
  ('cv_status', 'Loại', 0, '{"stage": "dung"}'::jsonb),
  ('cv_status', 'Phỏng vấn vòng 1', 1, '{"stage": "phong_van"}'::jsonb),
  ('cv_status', 'Phỏng vấn vòng 2', 2, '{"stage": "phong_van"}'::jsonb),
  ('cv_status', 'Phỏng vấn - loại', 3, '{"stage": "dung"}'::jsonb),
  ('cv_status', 'Chờ nhận việc', 4, '{"stage": "nhan_viec"}'::jsonb),
  ('cv_status', 'Nhận việc', 5, '{"stage": "nhan_viec"}'::jsonb),
  ('cv_status', 'Đang liên hệ', 6, '{"stage": "moi_ve"}'::jsonb),
  ('cv_status', 'Backup', 7, '{"stage": "cho_quyet_dinh"}'::jsonb),
  ('cv_status', 'Từ chối nhận việc', 8, '{"stage": "dung"}'::jsonb),
  ('cv_status', 'Không đến PV', 9, '{"stage": "dung"}'::jsonb),
  ('cv_status', 'Chưa lên hệ được', 10, '{"stage": "moi_ve"}'::jsonb),
  ('cv_status', 'PV đạt - backup', 11, '{"stage": "cho_quyet_dinh"}'::jsonb),
  ('cv_status', 'PV đạt - vòng 1', 12, '{"stage": "phong_van"}'::jsonb),
  ('stage', 'Mới về', 0, '{"key": "moi_ve"}'::jsonb),
  ('stage', 'Phỏng vấn', 1, '{"key": "phong_van"}'::jsonb),
  ('stage', 'Chờ quyết định', 2, '{"key": "cho_quyet_dinh"}'::jsonb),
  ('stage', 'Nhận việc', 3, '{"key": "nhan_viec"}'::jsonb),
  ('stage', 'Dừng', 4, '{"key": "dung"}'::jsonb),
  ('screener', 'Hân', 0, '{}'),
  ('screener', 'TTS Linh', 1, '{}'),
  ('screener', 'Thủy', 2, '{}'),
  ('interviewer', 'Ms Kim', 0, '{}'),
  ('interviewer', 'Ms Thu', 1, '{}'),
  ('interviewer', 'Ms Linh', 2, '{}'),
  ('interviewer', 'Ms Lan', 3, '{}'),
  ('interviewer', 'Mr Hải', 4, '{}'),
  ('interviewer', 'Mr Quang', 5, '{}'),
  ('interviewer', 'Mr Hiển', 6, '{}'),
  ('interviewer', 'Mr. Khải', 7, '{}'),
  ('interviewer', 'Ms. Ly', 8, '{}'),
  ('interviewer', 'Mr. Công', 9, '{}'),
  ('interviewer', 'Linh HCNS', 10, '{}'),
  ('interviewer', 'Ms Hải - KTT', 11, '{}'),
  ('interview_mode', 'Online', 0, '{}'),
  ('interview_mode', 'Offline HN', 1, '{}'),
  ('interview_mode', 'Offline HCM', 2, '{}'),
  ('interview_result', 'Đạt', 0, '{}'),
  ('interview_result', 'Không đạt', 1, '{}'),
  ('interview_result', 'Back up', 2, '{}'),
  ('offer_status', 'Đã gửi offer', 0, '{}'),
  ('offer_status', 'Chưa gửi offer', 1, '{}'),
  ('onboard_status', 'Pass 7 ngày thử việc', 0, '{}'),
  ('onboard_status', 'Không đạt sau 7 ngày thử việc', 1, '{}'),
  ('onboard_status', 'Pass 1 tháng thử việc', 2, '{}'),
  ('onboard_status', 'Pass 2 tháng thử việc', 3, '{}'),
  ('onboard_status', 'Nghỉ việc', 4, '{}'),
  ('onboard_status', 'Nhận việc', 5, '{}'),
  ('onboard_owner', 'Khuyên', 0, '{}'),
  ('onboard_owner', 'Chinh', 1, '{}'),
  ('onboard_owner', 'Diệu', 2, '{}'),
  ('onboard_owner', 'KA', 3, '{}'),
  ('onboard_owner', 'Ngọc', 4, '{}'),
  ('onboard_owner', 'Tên HR', 5, '{}'),
  ('onboard_owner', 'Trang', 6, '{}'),
  ('onboard_owner', 'TTS Nga', 7, '{}'),
  ('onboard_owner', 'Yến', 8, '{}'),
  ('onboard_owner', 'Linh', 9, '{}'),
  ('onboard_owner', 'Hân', 10, '{}'),
  ('onboard_owner', 'TTS Hiếu', 11, '{}'),
  ('onboard_owner', 'TTS Linh', 12, '{}'),
  ('onboard_owner', 'Thủy', 13, '{}'),
  ('onboard_office', 'Hà Nội', 0, '{}'),
  ('onboard_office', 'TP.HCM', 1, '{}'),
  ('onboard_task_group', 'Pre-onboard (1–3 ngày trước)', 0, '{"key": "pre"}'::jsonb),
  ('onboard_task_group', 'Ngày onboard', 1, '{"key": "ngay_onboard"}'::jsonb),
  ('onboard_task_group', 'Thông tin & tờ khai BHXH, thuế TNCN', 2, '{"key": "giay_to"}'::jsonb),
  ('onboard_task_group', 'Ký cam kết nhân sự', 3, '{"key": "cam_ket"}'::jsonb),
  ('onboard_task_group', 'Đào tạo và hội nhập', 4, '{"key": "dao_tao"}'::jsonb),
  ('onboard_task', 'Tạo group hội nhập / gửi ảnh chào mừng và dặn dò', 0, '{"key": "pre_group", "group": "pre"}'::jsonb),
  ('onboard_task', 'Chuẩn bị cơ sở vật chất', 1, '{"key": "pre_csvc", "group": "pre"}'::jsonb),
  ('onboard_task', 'UV đến onboard', 2, '{"key": "day_den", "group": "ngay_onboard"}'::jsonb),
  ('onboard_task', 'Tiếp nhận hồ sơ nhân viên onboard', 3, '{"key": "day_ho_so", "group": "ngay_onboard"}'::jsonb),
  ('onboard_task', 'Cấp phát trang thiết bị', 4, '{"key": "day_thiet_bi", "group": "ngay_onboard"}'::jsonb),
  ('onboard_task', 'Tờ khai tham gia BHXH', 5, '{"key": "kb_bhxh", "group": "giay_to"}'::jsonb),
  ('onboard_task', 'Tờ khai thuế TNCN (có MST)', 6, '{"key": "kb_tncn", "group": "giay_to"}'::jsonb),
  ('onboard_task', 'Giấy ủy quyền đăng ký MST TNCN (chưa có MST)', 7, '{"key": "kb_mst", "group": "giay_to"}'::jsonb),
  ('onboard_task', 'Cam kết sử dụng tài nguyên của công ty', 8, '{"key": "ck_tai_nguyen", "group": "cam_ket"}'::jsonb),
  ('onboard_task', 'Cam kết nộp đủ hồ sơ còn thiếu đúng thời hạn', 9, '{"key": "ck_ho_so", "group": "cam_ket"}'::jsonb),
  ('onboard_task', 'Ký xác nhận Quy định Chấm công', 10, '{"key": "ck_cham_cong", "group": "cam_ket"}'::jsonb),
  ('onboard_task', 'Ký xác nhận Quy định Đào tạo', 11, '{"key": "ck_dao_tao", "group": "cam_ket"}'::jsonb),
  ('onboard_task', 'Quy định về trách nhiệm bồi thường thiệt hại', 12, '{"key": "ck_boi_thuong", "group": "cam_ket"}'::jsonb),
  ('onboard_task', 'Giới thiệu về Doanh nghiệp', 13, '{"key": "dt_doanh_nghiep", "group": "dao_tao"}'::jsonb),
  ('onboard_task', 'Đào tạo về sản phẩm công ty (tùy vị trí)', 14, '{"key": "dt_san_pham", "group": "dao_tao"}'::jsonb),
  ('onboard_task', 'Đào tạo về ứng dụng AI', 15, '{"key": "dt_ai", "group": "dao_tao"}'::jsonb),
  ('onboard_task', 'Share tài liệu về AI', 16, '{"key": "dt_tai_lieu_ai", "group": "dao_tao"}'::jsonb)
on conflict (type, value) do update
  set sort_order = excluded.sort_order,
      meta       = excluded.meta,
      active     = true;
